apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686

  - name: ElasticSearch
    isDefault: true
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: https://opensearch:9200
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      index: "filebeat-*"
      esVersion: 70
      tlsSkipVerify: true
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: log.level
      dataLinks:
        - datasourceUid: jaeger
          field: "trace.id"
          url: "$${__value.raw}"
    secureJsonData:
      basicAuthPassword: admin

  - name: OpenSearch
    # isDefault: true
    uid: opensearch
    type: grafana-opensearch-datasource
    access: proxy
    url: https://opensearch:9200
    database: "filebeat-*"
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      database: "filebeat-*"
      flavor: "elasticsearch"
      logLevelField: "log.level"
      logMessageField: "message"
      maxConcurrentShardRequests: 5
      pplEnabled: true
      timeField: "@timestamp"
      tlsSkipVerify: true
      version: "7.10.2"
      dataLinks:
        - datasourceUid: jaeger
          field: "trace.id"
          url: "$${__value.raw}"
    secureJsonData:
      basicAuthPassword: admin
